name: Github Actions Workflow

on:
  
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env: 
  github_token: ${{ secrets.GithubActionWorkflowToken }}

permissions:
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          
      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          # creds: # ${{ secrets.AZURE_SPN_CREDENTIAL  }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: az bicep deploy 
        working-directory: '${{github.workspace}}/1.Sentinel-Bicep'
        run: |
            az deployment group create -g Sentinel-RG -f ./1.Create_LAW_Sentinel.bicep   

        